name: .NET Core CI/CD
# https://github.com/nogic1008/dotnet-ci-example/blob/master/.github/workflows/dotnetcore.yml
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"

jobs:
  test:
    name: Debug Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --settings coverlet.runsettings

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: "!**/.nuget/packages/**/*.*"
        flags: ${{ runner.os }},'3.1'

