name: .NET Core CI/CD
# https://github.com/nogic1008/dotnet-ci-example/blob/master/.github/workflows/dotnetcore.yml
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  test:
    name: Debug Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ubuntu-latest]
        # see also https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
        dotnet: [ { sdk: "3.1", framework: "netcoreapp3.1" }]
       
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core ${{ matrix.dotnet.sdk }} SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.sdk }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -f ${{ matrix.dotnet.framework }}
      - name: Test
        run: dotnet test -f ${{ matrix.dotnet.framework }} --settings coverlet.runsettings

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: "!**/.nuget/packages/**/*.*"
          flags: ${{ runner.os }},${{ matrix.dotnet.framework }}
