name: .NET Core CI/CD

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  test:
    name: Debug Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # see also https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
        dotnet: [ { sdk: "3.1", framework: "netcoreapp3.1" }, { sdk: "5.0", framework: "net5.0" } ]
        exclude:
          - os: windows-latest
            dotnet: { sdk: "3.1", framework: "netcoreapp3.1" }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ matrix.dotnet.sdk }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{ matrix.dotnet.sdk }}-
            ${{ runner.os }}-nuget-
      - name: Setup .NET Core ${{ matrix.dotnet.sdk }} SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet.sdk }}

      - name: Restore
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build --no-restore -f ${{ matrix.dotnet.framework }}
      - name: Test
        run: dotnet test --no-build -f ${{ matrix.dotnet.framework }} --settings coverlet.runsettings

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: "!**/.nuget/packages/**/*.*"
          flags: ${{ runner.os }},${{ matrix.dotnet.framework }}
